package com.zsxneil.bing.mappers;

import com.zsxneil.bing.model.LofterSeries;

import java.util.List;

public interface LofterSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    int insert(LofterSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    int insertSelective(LofterSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    LofterSeries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LofterSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lofter_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LofterSeries record);

    List<LofterSeries> getAllSeries();

    LofterSeries selectOneByLink(String seriesLink);
}