package com.zsxneil.bing.model;

public class LofterSeries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_series.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_series.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_series.pageNo
     *
     * @mbggenerated
     */
    private Integer pageno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_series.id
     *
     * @return the value of lofter_series.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_series.id
     *
     * @param id the value for lofter_series.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_series.link
     *
     * @return the value of lofter_series.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_series.link
     *
     * @param link the value for lofter_series.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_series.pageNo
     *
     * @return the value of lofter_series.pageNo
     *
     * @mbggenerated
     */
    public Integer getPageno() {
        return pageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_series.pageNo
     *
     * @param pageno the value for lofter_series.pageNo
     *
     * @mbggenerated
     */
    public void setPageno(Integer pageno) {
        this.pageno = pageno;
    }

    @Override
    public String toString() {
        return "LofterSeries{" +
                "id=" + id +
                ", link='" + link + '\'' +
                ", pageno=" + pageno +
                '}';
    }
}