package com.zsxneil.bing.model;

public class LofterImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_images.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_images.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lofter_images.referId
     *
     * @mbggenerated
     */
    private Integer referid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_images.id
     *
     * @return the value of lofter_images.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_images.id
     *
     * @param id the value for lofter_images.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_images.link
     *
     * @return the value of lofter_images.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_images.link
     *
     * @param link the value for lofter_images.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lofter_images.referId
     *
     * @return the value of lofter_images.referId
     *
     * @mbggenerated
     */
    public Integer getReferid() {
        return referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lofter_images.referId
     *
     * @param referid the value for lofter_images.referId
     *
     * @mbggenerated
     */
    public void setReferid(Integer referid) {
        this.referid = referid;
    }
}